"""users table

Revision ID: 192b5d39d1e4
Revises: d631893d2f90
Create Date: 2018-05-14 17:52:17.640117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192b5d39d1e4'
down_revision = 'd631893d2f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('password_hash', sa.String(), nullable=True),
                    sa.Column('organization_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['organization_id'],
                                            ['organizations.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
