"""remake entire db

Revision ID: 5dab81d94ebc
Revises:
Create Date: 2018-05-12 17:23:02.548167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dab81d94ebc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('company', sa.String(), nullable=True),
                    sa.Column('payee', sa.String(), nullable=True),
                    sa.Column('address1', sa.String(), nullable=True),
                    sa.Column('address2', sa.String(), nullable=True),
                    sa.Column('city', sa.String(), nullable=True),
                    sa.Column('state', sa.String(), nullable=True),
                    sa.Column('zip', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('organizations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('address1', sa.String(), nullable=True),
                    sa.Column('address2', sa.String(), nullable=True),
                    sa.Column('city', sa.String(), nullable=True),
                    sa.Column('state', sa.String(), nullable=True),
                    sa.Column('zip', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('bookings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('film', sa.String(), nullable=True),
                    sa.Column('program', sa.String(), nullable=True),
                    sa.Column('guarantee', sa.Integer(), nullable=True),
                    sa.Column('percentage', sa.Integer(), nullable=True),
                    sa.Column('start_date', sa.DateTime(), nullable=True),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.Column('gross', sa.Integer(), nullable=True),
                    sa.Column('settled', sa.Boolean(), nullable=True),
                    sa.Column('distributor_id', sa.Integer(), nullable=True),
                    sa.Column('organization_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['distributor_id'],
                                            ['distributors.id'], ),
                    sa.ForeignKeyConstraint(['organization_id'],
                                            ['organizations.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('payments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('check_number', sa.String(), nullable=True),
                    sa.Column('amount', sa.Integer(), nullable=True),
                    sa.Column('booking_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('bookings')
    op.drop_table('organizations')
    op.drop_table('distributors')
    # ### end Alembic commands ###
