"""create distributor & organization relationship

Revision ID: b69f77d380e2
Revises: 192b5d39d1e4
Create Date: 2018-06-05 23:54:14.606794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69f77d380e2'
down_revision = '192b5d39d1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(),
                                      nullable=True))
        batch_op.create_foreign_key('org_id', 'organizations',
                                    ['organization_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_constraint('org_id', type_='foreignkey')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
